uploads = []
generated = []

[[outputs]]
id = "kFDDtmrVQzIFuMEon2MOC"
uri = "file://CodePath_Пояснительная_записка.md"
type = "text"
title = "Пояснительная записка - CodePath"

[[outputs]]
id = "p66RB92NBfplZ4sQGjP_N"
uri = "file://CodePath_Пояснительная_записка.docx"
type = "word_document"
title = "Пояснительная записка CodePath с рамками, штампом и гиперссылками (.docx)"

[[outputs]]
id = "pNPI06vCzXnzXwWRAlS6e"
uri = "file://CodePath_IDEF0.png"
type = "image"
title = "Контекстная диаграмма IDEF0 — CodePath"

[[outputs]]
id = "NuNoSXLjyQXqaE97Vq-n-"
uri = "file://CodePath_UseCase.png"
type = "image"
title = "Диаграмма вариантов использования (Use Case) — CodePath"

[[outputs]]
id = "ubfvQfILdnMJNZPe_poZO"
uri = "file://attached_assets/CodePath_Пояснительная_записка.docx"
type = "word_document"
title = "CodePath — Пояснительная записка (.docx)"

[[outputs]]
id = "zSV44OcQMl7mW6p32roa8"
uri = "file://attached_assets/CodePath_cost_breakdown.png"
type = "image"
title = "Структура затрат на разработку CodePath — круговая диаграмма"

[[outputs]]
id = "9jv3MWrEXCYr5fRC1syIs"
uri = "file://attached_assets/CodePath_UseCase2.png"
type = "image"
title = "Диаграмма вариантов использования — CodePath"

[[outputs]]
id = "QJu8nGoPKLKLZMugScacd"
uri = "file://attached_assets/CodePath_DB_Schema.png"
type = "image"
title = "Схема базы данных — CodePath"
